######################################################################
# Automatically generated by qmake (2.01a) Thu Nov 30 05:03:39 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += time_for_retire.cpp
